name: Erlang CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Erlang
        uses: erlef/setup-beam@v1
        with:
          otp-version: 25.3  
          rebar3-version: 3.18.0

      - name: Compile project
        run: rebar3 compile

      - name: Run EUnit tests
        run: rebar3 eunit
